Remove support for RSpec < 3.4
Older versions of RSpec are incompatible with Rake 11.0 and later,
causing the following error:

```
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000001757f28>
gemfiles/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/rake_task.rb:82:in `define'
gemfiles/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/rake_task.rb:62:in `initialize'
```

The `last_comment` method was removed in Rake 11.0.